# Generated by Django 5.2.17 on 2026-09-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_custom_name_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypin',
            name='label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
