# Generated by Django 5.2.17 on 2026-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('items_requested', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
