# Generated by Django 5.2.17 on 2026-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='source',
            field=models.CharField(choices=[('web', 'Web Request'), ('manual', 'Manual')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='price_na',
            field=models.BooleanField(default=False),
        ),
    ]
