# Generated by Django 5.2.17 on 2026-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('chairs', 'Chairs'), ('tables', 'Tables'), ('linens', 'Linens & Cloths'), ('covers', 'Covers & Sashes'), ('tents', 'Tents & Canopies'), ('sound_light', 'Sound & Lights'), ('decor', 'Décor'), ('glassware', 'Glassware & Tableware'), ('other', 'Other')], default='other', max_length=60)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_in_use', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('used', 'Used'), ('worn', 'Worn')], default='good', max_length=10)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_stock_threshold', models.PositiveIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
