# Generated by Django 5.2.17 on 2026-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_url',
            field=models.CharField(blank=True, help_text='Path to the item photo shown on the quotation page.', max_length=255),
        ),
    ]
